package com.apartment.mybatis.mapper;

import com.apartment.mybatis.entity.Apartment;
import com.apartment.mybatis.entity.ApartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApartmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int countByExample(ApartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int deleteByExample(ApartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int insert(Apartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int insertSelective(Apartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	List<Apartment> selectByExample(ApartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	Apartment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") Apartment record,
			@Param("example") ApartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") Apartment record,
			@Param("example") ApartmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(Apartment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByPrimaryKey(Apartment record);
}