package com.apartment.mybatis.mapper;

import com.apartment.mybatis.entity.ShuShe;
import com.apartment.mybatis.entity.ShuSheExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShuSheMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int countByExample(ShuSheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int deleteByExample(ShuSheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int insert(ShuShe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int insertSelective(ShuShe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	List<ShuShe> selectByExample(ShuSheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	ShuShe selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByExampleSelective(@Param("record") ShuShe record,
			@Param("example") ShuSheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByExample(@Param("record") ShuShe record,
			@Param("example") ShuSheExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByPrimaryKeySelective(ShuShe record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sushe
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	int updateByPrimaryKey(ShuShe record);
}