package com.apartment.mybatis.entity;

public class Apartment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apartment.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apartment.apart_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String apartName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apartment.apart_room_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer apartRoomNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apartment.isdelete
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apartment.apart_place
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String apartPlace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column apartment.surplus_room_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer surplusRoomNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apartment.id
	 * @return  the value of apartment.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apartment.id
	 * @param id  the value for apartment.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apartment.apart_name
	 * @return  the value of apartment.apart_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getApartName() {
		return apartName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apartment.apart_name
	 * @param apartName  the value for apartment.apart_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setApartName(String apartName) {
		this.apartName = apartName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apartment.apart_room_num
	 * @return  the value of apartment.apart_room_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getApartRoomNum() {
		return apartRoomNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apartment.apart_room_num
	 * @param apartRoomNum  the value for apartment.apart_room_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setApartRoomNum(Integer apartRoomNum) {
		this.apartRoomNum = apartRoomNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apartment.isdelete
	 * @return  the value of apartment.isdelete
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apartment.isdelete
	 * @param isdelete  the value for apartment.isdelete
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apartment.apart_place
	 * @return  the value of apartment.apart_place
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getApartPlace() {
		return apartPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apartment.apart_place
	 * @param apartPlace  the value for apartment.apart_place
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setApartPlace(String apartPlace) {
		this.apartPlace = apartPlace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column apartment.surplus_room_num
	 * @return  the value of apartment.surplus_room_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getSurplusRoomNum() {
		return surplusRoomNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column apartment.surplus_room_num
	 * @param surplusRoomNum  the value for apartment.surplus_room_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setSurplusRoomNum(Integer surplusRoomNum) {
		this.surplusRoomNum = surplusRoomNum;
	}
}