package com.apartment.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class ApartmentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public ApartmentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andApartNameIsNull() {
			addCriterion("apart_name is null");
			return (Criteria) this;
		}

		public Criteria andApartNameIsNotNull() {
			addCriterion("apart_name is not null");
			return (Criteria) this;
		}

		public Criteria andApartNameEqualTo(String value) {
			addCriterion("apart_name =", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameNotEqualTo(String value) {
			addCriterion("apart_name <>", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameGreaterThan(String value) {
			addCriterion("apart_name >", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameGreaterThanOrEqualTo(String value) {
			addCriterion("apart_name >=", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameLessThan(String value) {
			addCriterion("apart_name <", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameLessThanOrEqualTo(String value) {
			addCriterion("apart_name <=", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameLike(String value) {
			addCriterion("apart_name like", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameNotLike(String value) {
			addCriterion("apart_name not like", value, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameIn(List<String> values) {
			addCriterion("apart_name in", values, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameNotIn(List<String> values) {
			addCriterion("apart_name not in", values, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameBetween(String value1, String value2) {
			addCriterion("apart_name between", value1, value2, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartNameNotBetween(String value1, String value2) {
			addCriterion("apart_name not between", value1, value2, "apartName");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumIsNull() {
			addCriterion("apart_room_num is null");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumIsNotNull() {
			addCriterion("apart_room_num is not null");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumEqualTo(Integer value) {
			addCriterion("apart_room_num =", value, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumNotEqualTo(Integer value) {
			addCriterion("apart_room_num <>", value, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumGreaterThan(Integer value) {
			addCriterion("apart_room_num >", value, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("apart_room_num >=", value, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumLessThan(Integer value) {
			addCriterion("apart_room_num <", value, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumLessThanOrEqualTo(Integer value) {
			addCriterion("apart_room_num <=", value, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumIn(List<Integer> values) {
			addCriterion("apart_room_num in", values, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumNotIn(List<Integer> values) {
			addCriterion("apart_room_num not in", values, "apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumBetween(Integer value1, Integer value2) {
			addCriterion("apart_room_num between", value1, value2,
					"apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andApartRoomNumNotBetween(Integer value1, Integer value2) {
			addCriterion("apart_room_num not between", value1, value2,
					"apartRoomNum");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIsNull() {
			addCriterion("isdelete is null");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIsNotNull() {
			addCriterion("isdelete is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeleteEqualTo(Integer value) {
			addCriterion("isdelete =", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotEqualTo(Integer value) {
			addCriterion("isdelete <>", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteGreaterThan(Integer value) {
			addCriterion("isdelete >", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
			addCriterion("isdelete >=", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteLessThan(Integer value) {
			addCriterion("isdelete <", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
			addCriterion("isdelete <=", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIn(List<Integer> values) {
			addCriterion("isdelete in", values, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotIn(List<Integer> values) {
			addCriterion("isdelete not in", values, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
			addCriterion("isdelete between", value1, value2, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
			addCriterion("isdelete not between", value1, value2, "isdelete");
			return (Criteria) this;
		}

		public Criteria andApartPlaceIsNull() {
			addCriterion("apart_place is null");
			return (Criteria) this;
		}

		public Criteria andApartPlaceIsNotNull() {
			addCriterion("apart_place is not null");
			return (Criteria) this;
		}

		public Criteria andApartPlaceEqualTo(String value) {
			addCriterion("apart_place =", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceNotEqualTo(String value) {
			addCriterion("apart_place <>", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceGreaterThan(String value) {
			addCriterion("apart_place >", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceGreaterThanOrEqualTo(String value) {
			addCriterion("apart_place >=", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceLessThan(String value) {
			addCriterion("apart_place <", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceLessThanOrEqualTo(String value) {
			addCriterion("apart_place <=", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceLike(String value) {
			addCriterion("apart_place like", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceNotLike(String value) {
			addCriterion("apart_place not like", value, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceIn(List<String> values) {
			addCriterion("apart_place in", values, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceNotIn(List<String> values) {
			addCriterion("apart_place not in", values, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceBetween(String value1, String value2) {
			addCriterion("apart_place between", value1, value2, "apartPlace");
			return (Criteria) this;
		}

		public Criteria andApartPlaceNotBetween(String value1, String value2) {
			addCriterion("apart_place not between", value1, value2,
					"apartPlace");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumIsNull() {
			addCriterion("surplus_room_num is null");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumIsNotNull() {
			addCriterion("surplus_room_num is not null");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumEqualTo(Integer value) {
			addCriterion("surplus_room_num =", value, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumNotEqualTo(Integer value) {
			addCriterion("surplus_room_num <>", value, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumGreaterThan(Integer value) {
			addCriterion("surplus_room_num >", value, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("surplus_room_num >=", value, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumLessThan(Integer value) {
			addCriterion("surplus_room_num <", value, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumLessThanOrEqualTo(Integer value) {
			addCriterion("surplus_room_num <=", value, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumIn(List<Integer> values) {
			addCriterion("surplus_room_num in", values, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumNotIn(List<Integer> values) {
			addCriterion("surplus_room_num not in", values, "surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumBetween(Integer value1, Integer value2) {
			addCriterion("surplus_room_num between", value1, value2,
					"surplusRoomNum");
			return (Criteria) this;
		}

		public Criteria andSurplusRoomNumNotBetween(Integer value1,
				Integer value2) {
			addCriterion("surplus_room_num not between", value1, value2,
					"surplusRoomNum");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table apartment
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table apartment
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 10 15:58:46 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}