package com.apartment.mybatis.entity;

public class ShuShe {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sushe.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sushe.sushe_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String susheName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sushe.apartment_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer apartmentNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sushe.sushe_people_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer sushePeopleNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sushe.isdelete
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sushe.surplus_people_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer surplusPeopleNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sushe.id
	 * @return  the value of sushe.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sushe.id
	 * @param id  the value for sushe.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sushe.sushe_name
	 * @return  the value of sushe.sushe_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getSusheName() {
		return susheName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sushe.sushe_name
	 * @param susheName  the value for sushe.sushe_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setSusheName(String susheName) {
		this.susheName = susheName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sushe.apartment_num
	 * @return  the value of sushe.apartment_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getApartmentNum() {
		return apartmentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sushe.apartment_num
	 * @param apartmentNum  the value for sushe.apartment_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setApartmentNum(Integer apartmentNum) {
		this.apartmentNum = apartmentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sushe.sushe_people_num
	 * @return  the value of sushe.sushe_people_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getSushePeopleNum() {
		return sushePeopleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sushe.sushe_people_num
	 * @param sushePeopleNum  the value for sushe.sushe_people_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setSushePeopleNum(Integer sushePeopleNum) {
		this.sushePeopleNum = sushePeopleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sushe.isdelete
	 * @return  the value of sushe.isdelete
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sushe.isdelete
	 * @param isdelete  the value for sushe.isdelete
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sushe.surplus_people_num
	 * @return  the value of sushe.surplus_people_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getSurplusPeopleNum() {
		return surplusPeopleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sushe.surplus_people_num
	 * @param surplusPeopleNum  the value for sushe.surplus_people_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setSurplusPeopleNum(Integer surplusPeopleNum) {
		this.surplusPeopleNum = surplusPeopleNum;
	}
}