package com.apartment.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StudentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public StudentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andStudentNumIsNull() {
			addCriterion("student_num is null");
			return (Criteria) this;
		}

		public Criteria andStudentNumIsNotNull() {
			addCriterion("student_num is not null");
			return (Criteria) this;
		}

		public Criteria andStudentNumEqualTo(String value) {
			addCriterion("student_num =", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumNotEqualTo(String value) {
			addCriterion("student_num <>", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumGreaterThan(String value) {
			addCriterion("student_num >", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumGreaterThanOrEqualTo(String value) {
			addCriterion("student_num >=", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumLessThan(String value) {
			addCriterion("student_num <", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumLessThanOrEqualTo(String value) {
			addCriterion("student_num <=", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumLike(String value) {
			addCriterion("student_num like", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumNotLike(String value) {
			addCriterion("student_num not like", value, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumIn(List<String> values) {
			addCriterion("student_num in", values, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumNotIn(List<String> values) {
			addCriterion("student_num not in", values, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumBetween(String value1, String value2) {
			addCriterion("student_num between", value1, value2, "studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNumNotBetween(String value1, String value2) {
			addCriterion("student_num not between", value1, value2,
					"studentNum");
			return (Criteria) this;
		}

		public Criteria andStudentNameIsNull() {
			addCriterion("student_name is null");
			return (Criteria) this;
		}

		public Criteria andStudentNameIsNotNull() {
			addCriterion("student_name is not null");
			return (Criteria) this;
		}

		public Criteria andStudentNameEqualTo(String value) {
			addCriterion("student_name =", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameNotEqualTo(String value) {
			addCriterion("student_name <>", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameGreaterThan(String value) {
			addCriterion("student_name >", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameGreaterThanOrEqualTo(String value) {
			addCriterion("student_name >=", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameLessThan(String value) {
			addCriterion("student_name <", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameLessThanOrEqualTo(String value) {
			addCriterion("student_name <=", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameLike(String value) {
			addCriterion("student_name like", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameNotLike(String value) {
			addCriterion("student_name not like", value, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameIn(List<String> values) {
			addCriterion("student_name in", values, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameNotIn(List<String> values) {
			addCriterion("student_name not in", values, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameBetween(String value1, String value2) {
			addCriterion("student_name between", value1, value2, "studentName");
			return (Criteria) this;
		}

		public Criteria andStudentNameNotBetween(String value1, String value2) {
			addCriterion("student_name not between", value1, value2,
					"studentName");
			return (Criteria) this;
		}

		public Criteria andStudentSexIsNull() {
			addCriterion("student_sex is null");
			return (Criteria) this;
		}

		public Criteria andStudentSexIsNotNull() {
			addCriterion("student_sex is not null");
			return (Criteria) this;
		}

		public Criteria andStudentSexEqualTo(String value) {
			addCriterion("student_sex =", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexNotEqualTo(String value) {
			addCriterion("student_sex <>", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexGreaterThan(String value) {
			addCriterion("student_sex >", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexGreaterThanOrEqualTo(String value) {
			addCriterion("student_sex >=", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexLessThan(String value) {
			addCriterion("student_sex <", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexLessThanOrEqualTo(String value) {
			addCriterion("student_sex <=", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexLike(String value) {
			addCriterion("student_sex like", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexNotLike(String value) {
			addCriterion("student_sex not like", value, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexIn(List<String> values) {
			addCriterion("student_sex in", values, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexNotIn(List<String> values) {
			addCriterion("student_sex not in", values, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexBetween(String value1, String value2) {
			addCriterion("student_sex between", value1, value2, "studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentSexNotBetween(String value1, String value2) {
			addCriterion("student_sex not between", value1, value2,
					"studentSex");
			return (Criteria) this;
		}

		public Criteria andStudentMajorIsNull() {
			addCriterion("student_major is null");
			return (Criteria) this;
		}

		public Criteria andStudentMajorIsNotNull() {
			addCriterion("student_major is not null");
			return (Criteria) this;
		}

		public Criteria andStudentMajorEqualTo(String value) {
			addCriterion("student_major =", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorNotEqualTo(String value) {
			addCriterion("student_major <>", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorGreaterThan(String value) {
			addCriterion("student_major >", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorGreaterThanOrEqualTo(String value) {
			addCriterion("student_major >=", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorLessThan(String value) {
			addCriterion("student_major <", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorLessThanOrEqualTo(String value) {
			addCriterion("student_major <=", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorLike(String value) {
			addCriterion("student_major like", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorNotLike(String value) {
			addCriterion("student_major not like", value, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorIn(List<String> values) {
			addCriterion("student_major in", values, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorNotIn(List<String> values) {
			addCriterion("student_major not in", values, "studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorBetween(String value1, String value2) {
			addCriterion("student_major between", value1, value2,
					"studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentMajorNotBetween(String value1, String value2) {
			addCriterion("student_major not between", value1, value2,
					"studentMajor");
			return (Criteria) this;
		}

		public Criteria andStudentContactIsNull() {
			addCriterion("student_contact is null");
			return (Criteria) this;
		}

		public Criteria andStudentContactIsNotNull() {
			addCriterion("student_contact is not null");
			return (Criteria) this;
		}

		public Criteria andStudentContactEqualTo(String value) {
			addCriterion("student_contact =", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactNotEqualTo(String value) {
			addCriterion("student_contact <>", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactGreaterThan(String value) {
			addCriterion("student_contact >", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactGreaterThanOrEqualTo(String value) {
			addCriterion("student_contact >=", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactLessThan(String value) {
			addCriterion("student_contact <", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactLessThanOrEqualTo(String value) {
			addCriterion("student_contact <=", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactLike(String value) {
			addCriterion("student_contact like", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactNotLike(String value) {
			addCriterion("student_contact not like", value, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactIn(List<String> values) {
			addCriterion("student_contact in", values, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactNotIn(List<String> values) {
			addCriterion("student_contact not in", values, "studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactBetween(String value1, String value2) {
			addCriterion("student_contact between", value1, value2,
					"studentContact");
			return (Criteria) this;
		}

		public Criteria andStudentContactNotBetween(String value1, String value2) {
			addCriterion("student_contact not between", value1, value2,
					"studentContact");
			return (Criteria) this;
		}

		public Criteria andSusheNumIsNull() {
			addCriterion("sushe_num is null");
			return (Criteria) this;
		}

		public Criteria andSusheNumIsNotNull() {
			addCriterion("sushe_num is not null");
			return (Criteria) this;
		}

		public Criteria andSusheNumEqualTo(String value) {
			addCriterion("sushe_num =", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumNotEqualTo(String value) {
			addCriterion("sushe_num <>", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumGreaterThan(String value) {
			addCriterion("sushe_num >", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumGreaterThanOrEqualTo(String value) {
			addCriterion("sushe_num >=", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumLessThan(String value) {
			addCriterion("sushe_num <", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumLessThanOrEqualTo(String value) {
			addCriterion("sushe_num <=", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumLike(String value) {
			addCriterion("sushe_num like", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumNotLike(String value) {
			addCriterion("sushe_num not like", value, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumIn(List<String> values) {
			addCriterion("sushe_num in", values, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumNotIn(List<String> values) {
			addCriterion("sushe_num not in", values, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumBetween(String value1, String value2) {
			addCriterion("sushe_num between", value1, value2, "susheNum");
			return (Criteria) this;
		}

		public Criteria andSusheNumNotBetween(String value1, String value2) {
			addCriterion("sushe_num not between", value1, value2, "susheNum");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeIsNull() {
			addCriterion("enrollment_time is null");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeIsNotNull() {
			addCriterion("enrollment_time is not null");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeEqualTo(Date value) {
			addCriterion("enrollment_time =", value, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeNotEqualTo(Date value) {
			addCriterion("enrollment_time <>", value, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeGreaterThan(Date value) {
			addCriterion("enrollment_time >", value, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("enrollment_time >=", value, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeLessThan(Date value) {
			addCriterion("enrollment_time <", value, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeLessThanOrEqualTo(Date value) {
			addCriterion("enrollment_time <=", value, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeIn(List<Date> values) {
			addCriterion("enrollment_time in", values, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeNotIn(List<Date> values) {
			addCriterion("enrollment_time not in", values, "enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeBetween(Date value1, Date value2) {
			addCriterion("enrollment_time between", value1, value2,
					"enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andEnrollmentTimeNotBetween(Date value1, Date value2) {
			addCriterion("enrollment_time not between", value1, value2,
					"enrollmentTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeIsNull() {
			addCriterion("graduation_time is null");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeIsNotNull() {
			addCriterion("graduation_time is not null");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeEqualTo(Date value) {
			addCriterion("graduation_time =", value, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeNotEqualTo(Date value) {
			addCriterion("graduation_time <>", value, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeGreaterThan(Date value) {
			addCriterion("graduation_time >", value, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("graduation_time >=", value, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeLessThan(Date value) {
			addCriterion("graduation_time <", value, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeLessThanOrEqualTo(Date value) {
			addCriterion("graduation_time <=", value, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeIn(List<Date> values) {
			addCriterion("graduation_time in", values, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeNotIn(List<Date> values) {
			addCriterion("graduation_time not in", values, "graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeBetween(Date value1, Date value2) {
			addCriterion("graduation_time between", value1, value2,
					"graduationTime");
			return (Criteria) this;
		}

		public Criteria andGraduationTimeNotBetween(Date value1, Date value2) {
			addCriterion("graduation_time not between", value1, value2,
					"graduationTime");
			return (Criteria) this;
		}

		public Criteria andIsdeteleIsNull() {
			addCriterion("isdetele is null");
			return (Criteria) this;
		}

		public Criteria andIsdeteleIsNotNull() {
			addCriterion("isdetele is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeteleEqualTo(Integer value) {
			addCriterion("isdetele =", value, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleNotEqualTo(Integer value) {
			addCriterion("isdetele <>", value, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleGreaterThan(Integer value) {
			addCriterion("isdetele >", value, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleGreaterThanOrEqualTo(Integer value) {
			addCriterion("isdetele >=", value, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleLessThan(Integer value) {
			addCriterion("isdetele <", value, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleLessThanOrEqualTo(Integer value) {
			addCriterion("isdetele <=", value, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleIn(List<Integer> values) {
			addCriterion("isdetele in", values, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleNotIn(List<Integer> values) {
			addCriterion("isdetele not in", values, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleBetween(Integer value1, Integer value2) {
			addCriterion("isdetele between", value1, value2, "isdetele");
			return (Criteria) this;
		}

		public Criteria andIsdeteleNotBetween(Integer value1, Integer value2) {
			addCriterion("isdetele not between", value1, value2, "isdetele");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table student
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 10 15:58:46 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}