package com.apartment.mybatis.entity;

import java.util.Date;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.student_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String studentNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.student_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String studentName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.student_sex
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String studentSex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.student_major
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String studentMajor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.student_contact
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String studentContact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.sushe_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private String susheNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.enrollment_time
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Date enrollmentTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.graduation_time
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Date graduationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.isdetele
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	private Integer isdetele;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.id
	 * @return  the value of student.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.id
	 * @param id  the value for student.id
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.student_num
	 * @return  the value of student.student_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getStudentNum() {
		return studentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.student_num
	 * @param studentNum  the value for student.student_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setStudentNum(String studentNum) {
		this.studentNum = studentNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.student_name
	 * @return  the value of student.student_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getStudentName() {
		return studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.student_name
	 * @param studentName  the value for student.student_name
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.student_sex
	 * @return  the value of student.student_sex
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getStudentSex() {
		return studentSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.student_sex
	 * @param studentSex  the value for student.student_sex
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setStudentSex(String studentSex) {
		this.studentSex = studentSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.student_major
	 * @return  the value of student.student_major
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getStudentMajor() {
		return studentMajor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.student_major
	 * @param studentMajor  the value for student.student_major
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setStudentMajor(String studentMajor) {
		this.studentMajor = studentMajor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.student_contact
	 * @return  the value of student.student_contact
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getStudentContact() {
		return studentContact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.student_contact
	 * @param studentContact  the value for student.student_contact
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setStudentContact(String studentContact) {
		this.studentContact = studentContact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.sushe_num
	 * @return  the value of student.sushe_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public String getSusheNum() {
		return susheNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.sushe_num
	 * @param susheNum  the value for student.sushe_num
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setSusheNum(String susheNum) {
		this.susheNum = susheNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.enrollment_time
	 * @return  the value of student.enrollment_time
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Date getEnrollmentTime() {
		return enrollmentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.enrollment_time
	 * @param enrollmentTime  the value for student.enrollment_time
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setEnrollmentTime(Date enrollmentTime) {
		this.enrollmentTime = enrollmentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.graduation_time
	 * @return  the value of student.graduation_time
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Date getGraduationTime() {
		return graduationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.graduation_time
	 * @param graduationTime  the value for student.graduation_time
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setGraduationTime(Date graduationTime) {
		this.graduationTime = graduationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.isdetele
	 * @return  the value of student.isdetele
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public Integer getIsdetele() {
		return isdetele;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.isdetele
	 * @param isdetele  the value for student.isdetele
	 * @mbggenerated  Thu Dec 10 17:31:36 GMT+08:00 2015
	 */
	public void setIsdetele(Integer isdetele) {
		this.isdetele = isdetele;
	}
}